### PR TITLE
Add `hash` keyword and subsequent changes.

### PR DESCRIPTION
**Pull request by theogf**
This is a potential solution to #114 

The code change is not so intense but it is breaking and I could understand if you would not be happy with this solution.

The idea is to store the `hash` function in `Indices`. One is then free to pass any function of his choice returning an appropriate `UInt` value.
So by passing `hash = objectid` we get exactly an `IdDict`.

The other needed change was the whole `insertion.jl` file, where the check where lenient and had some code repetition. 

Another strong change is the use of `Base.promote_typejoin` instead of `promote_type`. This means that when given an Array `[1, 2.0, 3.0]`, the type will default to `Real` instead of `Float64`.

I also set up the lower version to 1.6 out of convenience with the keyword passing syntax sugar.

### CODE REVIEW

**Comment by andyferris** [comment]
@theogf thanks for the contributions. This is indeed a tricky problem. 

There are a couple of complexities that need to be looked at here. 

So dictionary keys/indices deal with “equivalence classes” - only one key from each equivalence class may be stored.

The default equivalence class is given by `isequal` which differs from `==` in that it can be used to validly define equivalence classes (eg for `NaN`) and differs from `===` in that the equivalence classes may contain more than one thing. The `hash` function is there to help optimise lookup. We can alternatively use `isless` to make lookup faster (in a b-tree, say). In both cases the dictionaries would use `isequal` to disambiguate (explicitly in hash maps and perhaps implicitly in the case of `isless` due to the requirement that `isequal(x,y) == !(isless(x,y) || isless(y, x))`)

The equivalence classes for `IdDict` are given by `===`. This `objectid` function is both faster and is a better discriminant for these classes, but a ID dictionary would still function correctly with `hash`! So it is necessary to not only allow the user to specify the hash function but also the equality function. 

Relatedly is the type promotion. Due to the structure of equivalence classes of `isequal`, Julia is free to optimise certain data structures by restraining the types, and there are similar requirements on `promote` and `convert` that the equivalence class of the output is the same as the input (otherwise you should use a constructor or helper function to make your intended type). All these requirements are only sparsely documented. Dropping the `promote` optimization for the common case of using `isequal` is not ideal for performance reasons. 

Now having users specify multiple functions wouldn’t be very ergonomic. If we want to persue this we might want something like the built in `Order` struct to define ordering, which includes a few bits of data. That way common sets of equivalence classes could be provided and exposed equally. 

Finally we have discussed elsewhere an alternative approach using “mapped keys” where the key might be wrapped in some thing that then controls `isequal`, `hash`, conversion and promotion and even `isless`. Then the same mechanism could be used for hash maps, array dictionary, b-trees, etc.

Anyway that’s a lot of information. What do you think?

**Comment by theogf** [comment]
> a ID dictionary would still function correctly with `hash`

Is that true? Since `hash(2) == hash(2.0)`, there would be no way to distinguish the two.

> Dropping the promote optimization for the common case of using isequal is not ideal for performance reasons.

Yes, I agree, but using `promote_typejoin` is not that bad as it is also regularly used for `Tuple` objects.

> Now having users specify multiple functions wouldn’t be very ergonomic.

I am not sure what you mean here? In this case we only require one function.

> we have discussed elsewhere an alternative approach using “mapped keys” where the key might be wrapped in some thing that then controls isequal, hash, conversion and promotion and even isless.

I will look into this

> Anyway that’s a lot of information. What do you think?

So I am not sure what you propose from here? Should I look instead at the "mapped keys" solution as an implementation alternative?

**Comment by andyferris** [comment]
> Is that true? Since hash(2) == hash(2.0), there would be no way to distinguish the two.

So once you find two elements with the same hash, we still need to deal with possible hash collisions by then checking that `isequal(2, 2.0)`. For an ID dictionary this would instead check for `2 === 2.0`.

> I am not sure what you mean here? In this case we only require one function.

So the second function is using `===` instead of `isequal` to avoid hash collisions. A hash-based dictionary needs both `hash` and `isequal` (or `objectid` and `===`, or perhaps a user wants to specify their own).

> So I am not sure what you propose from here? Should I look instead at the "mapped keys" solution as an implementation alternative?

I'm thinking we have a few options:

## Option 1

We create an `Id` type and export it from Dictionaries.jl.

```julia
export Id

struct Id{T}
    value::T
end

isequal(x::Id, y::Id) = x.value === y.value
hash(x::Id) = objectid(x.value)
```

When a user wants an ID dictionary we _document_ that they should create and use one like so:

```julia
# we start with some objects that we want to use as keys
a = # ...
b = # ...

# create a dictionary and insert the keys using their `Id`
dict = Dictionary{Id{Any}, String}()
insert!(dict, Id(a), "this is a")
insert!(dict, Id(b), "this is b")

# Get something out and check it's what we want
@assert dict[Id(a)] == "this_is_a"
@assert haskey(dict, Id(b))
```

So it's quite a minimal change where the effort gets put on the user to some degree, but it's simple and elegant enough.

## Option 2

Introduce new types, perhaps called `MappedIndices` and `MappedIndicesDictionary` (a bit verbose!). These would apply transformations on the keys of a dictionary or indices (set) for the operations `gettoken` and `gettoken!`.

```julia
struct MappedIndices{I, Inds <: AbstractIndices, F} <: AbstractIndices{I}
    indices::Inds
    func::F
end

function gettoken(inds::MappedIndices, i)
    return gettoken(inds.indices, inds.f(i))
end

function gettoken!(inds::MappedIndices, i)
    return gettoken!(inds.indices, inds.f(i))
end
```

and similarly for `MappedIndicesDictionary` (implementation skipped).

One could use this together with `Id` in the first option:

```julia
dict = MappedIndicesDictionary{Any, String}(Id{Any})
insert!(dict, a, "this is a")
insert!(dict, b, "this is b")

# Get something out and check it's what we want
@assert dict[a] == "this_is_a"
@assert haskey(dict, b)
```

It's possible this will fit a few usage cases... we could e.g. add a finalizer for `WeakKeyDictionary` for example. It might be needed to define an inverse function to "unmap" the key (e.g. for iterating keys). I'm not yet sure if this option will play out nicely or not.

## Option 3

Allow the `hash` and `isequal` functions to be overridden for a hash-based dictionary. We'd create some object analogous to the `Order` object in `Base` to store the necessary stuff. Something like:

```julia
export Hash, STANDARD_HASH, ID_HASH

struct Hash{HashF, EqualF}
    hash::HashF
    isequal::EqualF
end

STANDARD_HASH = Hash(hash, isequal)
ID_HASH = Hash(objectid, ===)
```

We then add a new field to `Dictionary` and `UnorderedDictionary` to store these in a new `hash` field. A new type parameter on these would be required. Maybe we'd use keyword arguments to override these like this?

```julia
dict = Dictionary{Any, String}([a, b], ["this is a", "this is b"]; hash = ID_HASH) 

# Get something out and check it's what we want
@assert dict[a] == "this_is_a"
@assert haskey(dict, b)
```

It complicates the implementation and types of `Dictionary` and `UnorderedDictionary`, and I'm not yet sure if this option will play out nicely or not.

I hope that helps

**Comment by theogf** [comment]
Thanks a lot of for the detailed comment. I understand much better what you mean now.

All these approaches look really good. I think what I implemented more or less corresponds to an incomplete version to Option 3. So for me that would be the easiest to adapt.

I like elegance of Option 1.but one problem I see is that one would need to constantly unwrap the keys to access them.

I am not sure what is the difference between Option 2. and 3., I think the overridden `hash` should in any case belong to the `Indices` object. I guess Option 2. proposes to have a separate type of `AbstractIndices` where Option 3. would just modify the existing `Indices` object?

**Comment by theogf** [comment]
> So the second function is using === instead of isequal to avoid hash collisions. A hash-based dictionary needs both hash and isequal (or objectid and ===, or perhaps a user wants to specify their own pair of functions).

This is what I am not sure about. The docs state:
```
hash(x[, h::UInt]) -> UInt

  Compute an integer hash code such that isequal(x,y) implies hash(x)==hash(y). The optional
  second argument h is a hash code to be mixed with the result.
```
and
```
objectid(x) -> UInt

  Get a hash value for x based on object identity. objectid(x)==objectid(y) if x === y.
```

So the `hash` function directly implies what equivalence function we are using

**Comment by andyferris** [comment]
Note that `isequal(a, b)` implies `hash(a) == hash(b)` isn't the same thing as `hash(a) == hash(b)` implies `isequal(a, b)`.

Similarly `objectid(a, b)` does _not_ imply that `a === b` (using only raw pointers for `objectid` doesn't work in Julia because isbits values are not heap allocated, and their hashed `objectid` might collide with a pointer (or its hash)).

What we want the dictionary to do is identify when keys are `isequal` (or `===` in the case of ID dictionary) and the `hash` (or `objectid`) is just a way of ruling out the majority so we only have to make O(1) `isequal` (or `===`) checks instead of O(N) equality checks.

Think about how `ArrayIndices` and `ArrayDictionary` work. No `hash` is used and yet they satisfy the dictionary interface (although they use O(N) algorithms to do so).

The difference between options 2 and 3 is can I make an ID version of `ArrayDictionary`? What about an ID version of B-tree based `SortedDictionary`?

**Comment by theogf** [comment]
> Note that isequal(a, b) implies hash(a) == hash(b) isn't the same thing as hash(a) == hash(b) implies isequal(a, b).
> Similarly objectid(a, b) does not imply that a === b (using only raw pointers for objectid doesn't work in Julia because isbits values are not heap allocated, and their hashed objectid might collide with a pointer (or its hash)).

You're right, the implication is not going both ways.

> The difference between options 2 and 3 is can I make an ID version of ArrayDictionary? What about an ID version of B-tree based SortedDictionary?

Regarding Option 3., maybe you imply it, but shouldn't the `Hash` struct be a part of `Indices` (or any `AbstractIndices`)? In the end, if we call `keys(dict)` we still want to be able to access those `hash` and `isequal` functions no?

If that works for you, my next steps would then be to go with Option 3 and to implement it for all subtypes for `AbstractIndices`.

**Comment by theogf** [comment]
> Regarding Option 3., maybe you imply it, but shouldn't the Hash struct be a part of Indices (or any AbstractIndices)? In the end, if we call keys(dict) we still want to be able to access those hash and isequal functions no?

I digged a bit deeper and now I see that some `AbstractDictionary` don't always have indices from `AbstractIndices` so I now get your comment!

**Comment by serenity4** [comment]
To solve the specific issue you are raising @theogf (that of implementing an `IdDict`-like functionality in this package, #114), options 2 and 3 are almost identical. However, they greatly differ in the feature set they define for other use cases.

Option 3 does not require that keys be mapped to anything else, they stay the same. Only the hash and equality functions are modified, not the keys. I would believe that `Hash` should be part of the indices themselves (perhaps named `TokenMap` as hashing is only part of the semantics affected by the customization), and not stored in dictionaries (only indirectly through indices). Dictionary functions such as `dictionary` or `Dictionary` could expose this option and forward it to the indices.

Option 2 is more general. In a way, it is an automation of Option 1 and covers a much more general case, where one wants keys to behave as if they were semantically transformed for hash and equality functions. For example, under a transformation `x -> x / 2`, an index with value `4.0` will be acted upon as if it was `2.0` to generate tokens. `hash` and `isequal` will still be the only functions to be called, and their customization must go through by a type transformation with appropriate dispatches for `hash` and `isequal`. I believe that since the transformation is lazy and only used to retrieve tokens, the keys should remain the same (without the transformation) during iteration.

As I understand it:
- Option 1 allows the customization of `isequal` and `hash` functions by introducing new types and leveraging dispatches.
- Option 2 enables a lazy wrapping of indices to retrieve tokens.
- Option 3 allows direct customization of `isequal` and `hash` without changing indices or involving new types.

Option 3 directly solves #114. Option 2 requires the new `Id` type from Option 1 to solve #114. Option 1 puts the burden on the user to correctly map/unmap indices into/from the `Id` type, which is automated by Option 2.

I think that Option 1 is not the best one, as it can be a source of many bugs for a user that would forget from time to time that all indices are wrapped in a somewhat artifical `Id` type. I would not feel confident to define such a general feature as Option 2 considering #114 only; I believe we'd need other use cases to drive a proper implementation (and perhaps we would like to lazily transform keys for *any* use, e.g. iteration, not only for retrieving tokens). Option 3 has the advantage of being direct and require a low commitment in terms of API and design given that it only covers the use case we have in mind.

Therefore I would tend to lean towards a slightly modified version of Option 3, where `Hash` would have a more fitting name and where it would be stored in indices, not dictionaries.

**Comment by andyferris** [comment]
One disadvantage of option 3 is that we need to (a) implement it for every type of indices we want it for (e.g. `Indices`, `UnorderedIndices` and `ArrayIndices`) and (b) each of these gains another type parameter which will complicate things for users (e.g. porting from `Dict{K, T}` to `Dictionary{K, T, SomethingElse}` less straightforward than to just `Dictionary{K, T}` - keep in mind I would have code with dictionaries inside structs and I want them fast and type stable so users need to make sure they cover that).

I do see the point about making mistakes with `Id`. The fact that you couldn't convert to/from `Id` and it wouldn't have other methods defined means errors would likely be surfaced, at least. It has the advantage of not complicating other things.

Interesting considerations!

**Comment by andyferris** [comment]
I also note that we haven't really discussed the possiblity of doing what `Base` does and just introduce an `IdDictionary{K, T}` (and I guess `IdIndices{K}`), and leave everything else as-is? Could that be the least controversial change and least surprising to users?

**Comment by serenity4** [comment]
Indeed, the argument about having to change the number of type parameters and the impact on existing user code (and ergonomics of it) is quite strong.

At this stage, I would not be against defining an `IdDictionary` which wraps a `Dictionary` and which uses Option 1 under the hood so that most methods wrap/unwrap keys as needed so as to feel as if the wrapping into/from `Id` did not exist. That would also have the advantage of being more aligned with the relationship between `IdDict` and `Dict` in Base and it should not impact nor complexify existing code. Would you identify any issues with that?

We can also localize the wrapping/unwrapping to `IdIndices` as you mention and define `IdDictionary{K,V}` as `Dictionary{IdIndices{K}, V}`.

**Comment by andyferris** [comment]
@serenity4 yes that’s pretty much where my head is at, too.

The type at the end - did you mean `Dictionary{Id{K}, T}`? There will likely need to be a wrapper type for indices and a wrapper type for dictionary, plus a bit of handling around keys and similar and so-on. 

@theogf did you have any thoughts on this plan?

**Comment by theogf** [comment]
Hey @andyferris , I will close this one and restart another cleaner branch to tackle the latest solution proposed.

**Pull request closed without merging**
