### PR TITLE
Add convert method to `Dictionary`

### PR DESCRIPTION
**Pull request by serenity4**
This implements a very basic method to automatically convert between `Dictionary` types. I am not sure whether there is anything more to do.

Solves #66.

### CODE REVIEW

**Review by andyferris — APPROVED** [review]
Thanks @serenity4. Sorry I took so long to get to this.

(I modified your test a little bit)

We should try expand this to work for all `AbstractDictionary` somehow, in the future.

**Comment by serenity4** [comment]
Yes, it would be nice to make it work for all types of dictionaries. I'm not sure if there is a generic way to do it on `AbstractDictionary` that could work regardless of the implementation, though it might be reasonable to have a default conversion behavior that can be customized for dictionary implementations.

**Comment by andyferris** [comment]
I know in `Base` there are methods like `convert(::Type{AbstractVector{T}}, v::Vector) where {T} = Vector{T}(v)`. I think we could do that kind of thing here? I'm happy to merge this now and address it in the future though.

**Comment by andyferris** [comment]
FYI https://github.com/JuliaRegistries/General/pull/45174

**Comment by serenity4** [comment]
Thanks! Indeed there might be a way to do it cleanly. I personally needed this for `Dictionary` at the moment, but I'd be happy to revisit that in the future if needed.

**Pull request merged**
