### PR TITLE
Replace `HashDictionary` with an ordered hash dictionary

### PR DESCRIPTION
**Pull request by andyferris**
The new implementation preserves insertion order. It may use slightly more memory overall but is much faster to iterate because the indices/values are stored (somewhat) densely (performance comparable to `Vector`, i.e. limited by memory bandwidth). Faster insertion/deletion/resizing due to less need to call `hash` (hashes are recorded). Compared to OrderedCollections.jl this implementation (a) does not mutate the object on reads, like iteration (which can't be thread-safe) and (b) may theoretically deal better with deletion without slowdowns. Implementation is somewhat inspired by Python 3.6 ordered dictionary.

This PR now includes new functions `distinct` and `index`. The constructors for `HashIndices` and `HashDictionary` has been improved.

Things to do:

 - [x] `copy` optimization
 - [x] `filter!` optimization
 - [x] make `sizehint`s safe!
 - [x] add performance benchmarks to repository
 - [x] ensure `HashIndices` input is uniquified (or throw an error?)
 - [x] ~~think about adding a linear probing cut-off, double-check resizing...~~ it's good enough and pretty well tested, can revisit for speed purposes

This PR obviously leaves Dictionaries.jl with only ordered collections - so we are free to add more semantics to `AbstractIndices` and `AbstractDictionary` - things to think about include `sort`, `sortperm`, `permute!`, `push!`/`pop!`/`splice!` (these aren't collections of `Pair`s though).

### CODE REVIEW

**Comment by c42f** [comment]
Hey Andy, sorry I haven't reviewed yet, this diff is kind of epic!

I assume the best strategy would be to read the entirety of HashDictionary.jl and HashIndices.jl?  The diffs look pretty useless as it's a big rewrite... and I didn't know the previous code anyway.

**Comment by andyferris** [comment]
Yes it’s a brand new implementation of a hash map based on a python 3.6 talk I saw regarding their then-new implementation. 

My first hash map so it scares me! I need to copy some tests or something.

**Comment by andyferris** [comment]
OK this is getting super close. Benchmark suite is working, results are mostly good. The delete operation appears to be a bit slower than for `Set` or `Dictionaries.OldHashIndices` (which impacts other operations) so that needs investigating. On the other hand, operations like `filter!` (to few) and reductions are like totally rediculously awesome :)

**Comment by c42f** [comment]
Bravo, this looks epic. Sorry I didn't get around to reviewing it!

**Pull request merged**
